# Generated by Django 5.2.7 on 2025-11-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateTimeField()),
                ('joined_on', models.DateTimeField()),
                ('phone_number', models.CharField(max_length=8)),
                ('position', models.CharField(max_length=50)),
            ],
        ),
    ]
